sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

language: php

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.2
      env: COMPOSER_OPTIONS=""

before_install:
  - phpenv config-rm xdebug.ini
  - if [ "$COMPOSER_OPTIONS" = "" ]; then composer config minimum-stability dev; fi

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpstan analyze -l 6 src
  - vendor/bin/simple-phpunit
